### ISSUE TITLE
Jekyll post text shown at top of the page

### ISSUE THREAD

**Issue by adarshnair01** [joshgerdes/jekyll-uno#69] opened 2017-06-30 04:56 UTC
![screenshot from 2017-06-30 10-25-21](https://user-images.githubusercontent.com/7417427/27721552-a0a75d86-5d7e-11e7-8334-c615c9f7b1d9.png)

**Comment by joshsoucie** [comment] 2017-07-03 05:57
Same issue. Only showing when viewing a post - not on home page, or in post listings.

Seems to be in the head.html include file

`<meta name="description" content="{% if page.excerpt %}{{ page.excerpt | remove: '<p>' | remove: '</p>' }}{% else %}{{ site.description }}{% endif %}">
`

Renders in the demo site fine - pulls `site.description` as intended and includes as meta-tag (no excerpts for whatever reason?).

**Comment by joshsoucie** [comment] 2017-07-03 06:00
Did a little more digging...appears that in Pull-Request #62 this code was added

`<meta name="description" content="{% if page.excerpt %}{{ page.excerpt | remove: '<p>' | remove: '</p>' }}{% else %}{{ site.description }}{% endif %}">`

It's probably better if it reads:

`<meta name="description" content="{% if page.excerpt %}{{ page.excerpt | strip_html }}{% else %}{{ site.description }}{% endif %}">`

Using `| strip_html` instead of removing the p-tags manually.

Works correctly on my local build. Pushing to live site. Will update.

**Comment by joshsoucie** [comment] 2017-07-03 06:02
Seems this is an open pull-request #68.

Thanks @concrete-mixer

**Comment by tomajask** [comment] 2017-07-06 07:15
I had the same issue. Fix from #68 works like a charm! Thanks @js-bone21 & @concrete-mixer!

**Comment by ghost** [comment] 2017-07-31 21:52
yeah, #68 is the solution, thanks @js-bone21 and @concrete-mixer. While waiting for @joshgerdes to merge, I have merged this locally and pushed back to my fork, in case someone needs.
https://github.com/hoangdangninh/jekyll-uno

**Closed as completed** 2019-09-24 16:16 UTC
